In [1]:
import pandas as pd

df = pd.read_csv("/content/BankChurners.csv")
df.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.99991
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.99994
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.99998
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.99987
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.99998

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 23 columns):
 #   Column                                                                                                                              Non-Null Count  Dtype
---  ------                                                                                                                              --------------  -----
 0   CLIENTNUM                                                                                                                           10127 non-null  int64
 1   Attrition_Flag                                                                                                                      10127 non-null  object
 2   Customer_Age                                                                                                                        10127 non-null  int64
 3   Gender                                                                                                                              10127 non-null  object
 4   Dependent_count                                                                                                                     10127 non-null  int64
 5   Education_Level                                                                                                                     10127 non-null  object
 6   Marital_Status                                                                                                                      10127 non-null  object
 7   Income_Category                                                                                                                     10127 non-null  object
 8   Card_Category                                                                                                                       10127 non-null  object
 9   Months_on_book                                                                                                                      10127 non-null  int64
 10  Total_Relationship_Count                                                                                                            10127 non-null  int64
 11  Months_Inactive_12_mon                                                                                                              10127 non-null  int64
 12  Contacts_Count_12_mon                                                                                                               10127 non-null  int64
 13  Credit_Limit                                                                                                                        10127 non-null  float64
 14  Total_Revolving_Bal                                                                                                                 10127 non-null  int64
 15  Avg_Open_To_Buy                                                                                                                     10127 non-null  float64
 16  Total_Amt_Chng_Q4_Q1                                                                                                                10127 non-null  float64
 17  Total_Trans_Amt                                                                                                                     10127 non-null  int64
 18  Total_Trans_Ct                                                                                                                      10127 non-null  int64
 19  Total_Ct_Chng_Q4_Q1                                                                                                                 10127 non-null  float64
 20  Avg_Utilization_Ratio                                                                                                               10127 non-null  float64
 21  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1  10127 non-null  float64
 22  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2  10127 non-null  float64
dtypes: float64(7), int64(10), object(6)
memory usage: 1.8+ MB

In [3]:
df.shape

(10127, 23)

In [4]:
df['Attrition_Flag'].value_counts()

Attrition_Flag
Existing Customer    8500
Attrited Customer    1627
Name: count, dtype: int64

In [5]:
df['Attrition_Flag'].value_counts(normalize=True)

Attrition_Flag
Existing Customer    0.83934
Attrited Customer    0.16066
Name: proportion, dtype: float64

In [6]:
df.columns

Index(['CLIENTNUM', 'Attrition_Flag', 'Customer_Age', 'Gender',
       'Dependent_count', 'Education_Level', 'Marital_Status',
       'Income_Category', 'Card_Category', 'Months_on_book',
       'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio',
       'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1',
       'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'],
      dtype='object')

In [7]:
bins = [0, 29, 39, 49, 59, 100]
labels = ["<30", "30-39", "40-49", "50-59", ">60"]

df["age_group"] = pd.cut(df["Customer_Age"], bins=bins, labels=labels)

In [8]:
df["churn"] = (df["Attrition_Flag"] == "Attrited Customer")

In [9]:
df["churn"] = (df["Attrition_Flag"] == "Attrited Customer").astype(int)

In [10]:
df.groupby("age_group")["churn"].mean().sort_values(ascending=False)

/tmp/ipython-input-3414433039.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("age_group")["churn"].mean().sort_values(ascending=False)

age_group
40-49    0.169261
50-59    0.168779
30-39    0.141771
>60      0.133459
<30      0.087179
Name: churn, dtype: float64

In [11]:
df.groupby('Gender')["churn"].mean().sort_values(ascending=False)

Gender
F    0.173572
M    0.146152
Name: churn, dtype: float64

In [12]:
df.groupby('Education_Level')["churn"].mean().sort_values(ascending=False)

Education_Level
Doctorate        0.210643
Post-Graduate    0.178295
Unknown          0.168532
Uneducated       0.159381
Graduate         0.155691
College          0.152024
High School      0.152012
Name: churn, dtype: float64

In [13]:
df.groupby('Marital_Status')["churn"].mean().sort_values(ascending=False)

Marital_Status
Unknown     0.172230
Single      0.169414
Divorced    0.161765
Married     0.151269
Name: churn, dtype: float64

In [14]:
df.groupby('Income_Category')["churn"].mean().sort_values(ascending=False)

Income_Category
$120K +           0.173315
Less than $40K    0.171862
Unknown           0.168165
$80K - $120K      0.157655
$40K - $60K       0.151397
$60K - $80K       0.134807
Name: churn, dtype: float64

In [15]:
df.groupby('Attrition_Flag')[['Total_Trans_Ct', 'Total_Trans_Amt', 'Avg_Utilization_Ratio', 'Months_Inactive_12_mon']].mean()

,Total_Trans_Ct,Total_Trans_Amt,Avg_Utilization_Ratio,Months_Inactive_12_mon
Attrition_Flag,,,,
Attrited Customer,44.933620,3095.025814,0.162475,2.693301
Existing Customer,68.672588,4654.655882,0.296412,2.273765

In [16]:
df.groupby('Attrition_Flag')[['Credit_Limit', 'Total_Revolving_Bal']].mean()

                   Credit_Limit  Total_Revolving_Bal
Attrition_Flag
Attrited Customer   8136.039459           672.822987
Existing Customer   8726.877518          1256.604118